language: java

sudo: true

services:
- mysql

before_install:
- echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
- wget https://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
- sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
- sudo apt-get update -q
- sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
- sudo mysql_upgrade
- sudo apt-get update -y
- sudo service mysql restart
- cd TaskManager
- chmod +x gradlew
- ./gradlew clean

jdk:
- oraclejdk8

notifications:
email:
- francoluigi95@gmail.com
- davidecocca@gmail.com
- giovannipirozzi95@gmail.com
on_success: never
on_failure: always

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  
#Setting MySQL Configuration in Travis CI
- cat ~travis/.my.cnf


sudo: required
dist: trusty
group: stable
