language: java
language: android

sudo: true

jdk:
- oraclejdk8

services:
- mysql

before_install:
- echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
- wget https://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
- sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
- sudo apt-get update -q
- sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
- sudo mysql_upgrade
- sudo apt-get update -y
- sudo service mysql restart
- cd TaskManager
- chmod +x gradlew
- ./gradlew clean

 android:
   components:
     - build-tools-28.0.2
     - android-28
     - android-24
     - sys-img-armeabi-v7a-android-24
     - tools
     - platform-tools
       
   # Additional components
   - extra-android-support
   - extra-google-google_play_service
   - extra-google-m2repository
   - extra-android-m2repository
   - addon-google_apis-google-19

  
   
before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
- cd ..
- cd TaskManagerAndroidClient
- chmod +x gradlew
- ./gradlew connectedAndroidTest

notifications:
email:
- francoluigi95@gmail.com
- davidecocca@gmail.com
- giovannipirozzi95@gmail.com
on_success: never
on_failure: always

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  


sudo: required
dist: trusty
group: stable
